### ISSUE TITLE
录制报错Record command report error

### ISSUE THREAD

**Issue by bsshanghai** [appetizerio/appetizer-toolkit#10]
![image](https://user-images.githubusercontent.com/28524371/37641292-1fad9a9c-2c54-11e8-8217-cec62714e979.png)
1.首次运行如上报错。exit后在录制一遍，又正常了。

![image](https://user-images.githubusercontent.com/28524371/37641496-ead7c378-2c54-11e8-8ef2-782fc19067b1.png)
2.如上。查看录制的情况的命令报错
3.此外发现录制的最后一个命令，如果是点击，有可能被吃掉，就是replay的时候没有执行，exit太早了？或者最后一个点击操作会变成长按，等一会再exit就会如此。

**Comment by mingyuan-xia** [comment]
1. 的问题是adb 没有启动，你看看 `adb devices`是否正常
2. 进入`appetizer >`就是已经开始录制了，先要结束录制 `exit`退回正常命令行，再 `appetizer trace info trace.txt`
3. 最后一个被吃掉（按下但是不抬起）问题已知，正在排查

**Comment by bsshanghai** [comment]
谢谢谢谢
1.确实是的。
2.刚才也在录制结束后重新运行得到了正确结果.
3.就再等等咯。加油！
