### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by baranpirincal** [appetizerio/appetizer-toolkit#17]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by mingyuan-xia** [comment]
Thank you for the proposal. Replaykit is an affiliate project of [Appetizer](https://appetizer.io) and it is not currently expecting an independent new logo.
