### ISSUE TITLE
是否对Genymotion模拟器的输入框定位和支持有问题？

### ISSUE THREAD

**Issue by Archer456** [appetizerio/appetizer-toolkit#6]
用的Genymotion模拟器 ，模拟镜像Samsung Galaxy S6 -6.0.0-API23 为。
操作一APP 到注册页面，然后输入用户名和密码。录制过程中，报出来了一些警告。
![image](https://user-images.githubusercontent.com/18392901/31367004-fb24ad36-ada6-11e7-94c8-72c6cb8561e7.png)

再回放时候，发现到注册页面，就中止了，没有进行输入用户名和密码操作。
`C:\Users\cmd>appetizer trace info sg6.trace
{"contacts": 1, "description": "", "height": 800, "length": 14.967434000000026, "records": 48, "valid": true, "width": 480}

C:\Users\cmd>appetizer trace replay -h
usage: appetizer trace replay [-h] [--port PORT] [--host HOST]
                              trace_file device_list

positional arguments:
  trace_file            Path to the trace file
  device_list           Comma-separated device serial numbers

optional arguments:
  -h, --help            show this help message and exit
  --port PORT, -P PORT  ADB server port
  --host HOST, -H HOST  ADB server host

C:\Users\cmd>appetizer trace replay sg6.trace 192.168.60.101:5555
appetizer>`

回放并没有给什么日志  放完就自动退出命令行了。

是不是 对Genymotion模拟器的输入框定位有问题 。 哦 模拟器都是用鼠标和键盘操作的，是不是应该用真机USB链接 更好些？

**Comment by Archer456** [comment]
另外 问个问题  .trace文件 是存放在哪个路径下的。

**Comment by Azard** [comment]
@mingyuan-xia 

第二个问题，.trace 文件是命令行输入的时候 record 的最后一个参数，随意存放在哪里。
``C:\Users\cmd>appetizer trace info sg6.trace` 就是存放在 `C:\Users\cmd\sg6.trace`

**Comment by RealLau** [comment]
@Archer456 也就是在你当前执行命令的目录下

**Comment by Archer456** [comment]
3Q 找到了   居然是个 wireshark capure file 。
那个 第一个问题  是不是 模拟器 是鼠标和键盘操作  输入上不是模拟器手机内的键盘输入的  所以没录制到？   录制 我看你们说 不是说 基于 坐标么？

**Comment by Archer456** [comment]
WARNING: linker: /system/lib/libhoudini.so has text relocations. This is wasting memory and prevents security hardening. Please fix.

虚拟器 执行相关appetizer命令  老报这个警告  请问怎么处理？

**Comment by Archer456** [comment]
谢谢 已经自己解决了 
“模拟器都是用鼠标和键盘操作的”   
我设置下genymotion 的 use vitualkeyboard  for text input 使用这个输入 就可录制了。

**Comment by mingyuan-xia** [comment]
恩，我以前用过genymotion mirror到Nexus 5 ，没问题的，反过来也可以，感谢提供设置 :-)
