### ISSUE TITLE
如何为trace文件添加描述？

### ISSUE THREAD

**Issue by Bingao-hn** [appetizerio/appetizer-toolkit#7]
使用appetizer trace info mytrace.trace来查看trace文件，发现describe为空，但是也没有找到相关的指令来输入描述；请问有相关指令吗？谢谢！

**Comment by mingyuan-xia** [comment]
这个版本没有，下个加

**Comment by Bingao-hn** [comment]
谢谢回复！因为看到这个选项，但是又没有相应指令，所以觉得很奇怪。

**Comment by mingyuan-xia** [comment]
`replaykit trace describe mytrace.trace "this is a new description for it"`
1.0.7 版本
