### ISSUE TITLE
华为为主设备镜像操作问题

### ISSUE THREAD

**Issue by luffy7272** [appetizerio/appetizer-toolkit#9]
镜像操作主设备是华为的时候，子设备每一个动作结束后都保持按着屏幕不放的状态
![ki7d 5hy x4brgs 5_rs n](https://user-images.githubusercontent.com/16202559/36775377-c6b34f5c-1c9c-11e8-995a-2b9b28803cca.jpg)

**Comment by mingyuan-xia** [comment]
#5 重复 一并修复
